### PR TITLE
Remove files from disk if settings.DELETE_ATTACHMENTS_FROM_DISK

### PR DESCRIPTION
**Pull request by atodorov**
@bartTC please review.

### CODE REVIEW

**Comment by atodorov** [comment]
@bartTC can you check this out? I will write the missing tests but I need some opinion on the general approach in this PR

**Comment by bartTC** [comment]
@atodorov I think this is fine. I was trying to figure out if this is something we actually have to do, or if the FileField can handle this automatically once it'smodel gets deleted.

**Comment by atodorov** [comment]
> I was trying to figure out if this is something we actually have to do, or if the FileField can handle this automatically once it'smodel gets deleted.

From
https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.fields.files.FieldFile.delete

> Note that when a model is deleted, related files are not deleted. If you need to cleanup orphaned files, you’ll need to handle it yourself 

It looks like deleting files automatically has been removed in Django 1.3:
https://docs.djangoproject.com/en/2.0/releases/1.3/#deleting-a-model-doesn-t-delete-associated-files


I will go ahead and write the missing tests.

**Comment by bartTC** [comment]
Interesting. Thank you, this is a nice addition!

**Pull request merged**
