### PR TITLE
Add manage.py command to delete stale attachments

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by bartTC** [comment]
This is a great addition. Would you briefly document this in the README?

**Comment by atodorov** [comment]
@bartTC I've added a section in README but then realized this implementation was incomplete b/c `Attachment.delete()` will still leave files on disk. I've added a call to `remove_file_from_disk()` as well.

**Comment by atodorov** [comment]
Related to my latest comment: I've been using custom signal handlers to remove attachments when a related object gets removed in a project of mine but forgot about `remove_files_from_disk()`. I think it is time to override `.delete()` on the model and manager to handle this, don't you think ?

**Comment by atodorov** [comment]
@bartTC should I go ahead and merge this and the rest of my PRs or you prefer giving them a look over first ?

**Pull request merged**
