### PR TITLE
Django 3

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@bartTC I wouldn't mind if you can push a new minor version to PyPI soon. Hope this helps.

**Comment by bartTC** [comment]
Thank you. https://pypi.org/project/django-attachments/

**Comment by atodorov** [comment]
@bartTC can you push 1.5 wheel package to PyPI ?

**Comment by bartTC** [comment]
Its in

**Comment by atodorov** [comment]
thanks a lot

**Pull request merged**
