### PR TITLE
Helper template tags to display name and size of the attachment

### PR DESCRIPTION
**Pull request by morlandi**
Nothing particularly exciting, but sometimes handy

### CODE REVIEW

**Comment by morlandi** [comment]
Any interest in this PR ? In case, I'll add a specific unit test to it

**Comment by bartTC** [comment]
Thank you for your effort but I dont think these are necessary. Note that the filename is already provided by the model and does not need an extra templatetag.

https://github.com/bartTC/django-attachments/blob/master/attachments/models.py#L63

Please see also https://docs.python.org/2/howto/doanddont.html#except

**Comment by morlandi** [comment]
Thank you @bartTC for your comments; I totally agree.

Concerning https://docs.python.org/2/howto/doanddont.html#except ... I do believe that a templatetag should never ever throw an exception, but I might be wrong.
If this is the case, intercepting a specific type of exception doesn't always fit the bill.
What to you think ?

**Comment by bartTC** [comment]
What makes a templatetag different from the rest of the Python code? If you really want to avoid any chance of errors you should use settings.DEBUG. 

```
if settings.DEBUG
  raise
else
  pass```

**Comment by morlandi** [comment]
I'm sure I've read that Django "prescribes" for any templatetag not to raise any exception ever, but I don't remember where and when I read it, so this might very well be an obsolete or a silly suggestion.

**Pull request closed without merging**
